version: '3.4'
 
networks:
    cryptoapp:    
        driver: bridge  

volumes:
    db-data:
 
services:
    db:
        image: mcr.microsoft.com/mssql/server:2019-CU21-ubuntu-20.04
        restart: always
        ports:
            - 6474:1433
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=a24746@svalero.com
        networks:
            - cryptoapp
        volumes:
            - db-data:/var/opt/mssql
        healthcheck:
            test: ["CMD", "sqlcmd", "-U", "sa", "-P", "a24746@svalero.com", "-Q", "SELECT 1"]
            interval: 30s
            timeout: 10s
            retries: 3
    api:
        restart: unless-stopped 
        ports:
            - 4746:80 
        build:
          context: .
          dockerfile: API/Dockerfile
        depends_on:
            - db
        networks:
            - cryptoapp

    #web:
        #container_name: webContainer
        #image: web:1.0
        #ports:
            #- 9000:8080 
        #depends_on:
            #- api